"""add currency_rate table

Revision ID: 942bb70c2208
Revises: 678a1c21167d
Create Date: 2025-08-07 22:09:06.144733

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942bb70c2208'
down_revision: Union[str, Sequence[str], None] = '678a1c21167d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rate',
    sa.Column('currency_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('base_currency_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('data_source_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currency.id'], name=op.f('fk_currency_rate_base_currency_id_currency')),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name=op.f('fk_currency_rate_currency_id_currency')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_currency_rate_data_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_rate')),
    sa.UniqueConstraint('currency_id', 'date', 'base_currency_id', name='uix_currency_date_base')
    )
    op.create_index('ix_currency_rate_currency_date', 'currency_rate', ['currency_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_rate_currency_date', table_name='currency_rate')
    op.drop_table('currency_rate')
    # ### end Alembic commands ###
