"""currency remove datacourse_id

Revision ID: cf8edf9fb646
Revises: dc75c5dd6757
Create Date: 2025-08-13 18:59:21.743643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8edf9fb646'
down_revision: Union[str, Sequence[str], None] = 'dc75c5dd6757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_code_data_source_id'), 'currency', type_='unique')
    op.create_unique_constraint(op.f('uq_currency_code'), 'currency', ['code'])
    op.drop_constraint(op.f('fk_currency_data_source_id_data_source'), 'currency', type_='foreignkey')
    op.drop_column('currency', 'data_source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('data_source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_currency_data_source_id_data_source'), 'currency', 'data_source', ['data_source_id'], ['id'])
    op.drop_constraint(op.f('uq_currency_code'), 'currency', type_='unique')
    op.create_unique_constraint(op.f('uix_code_data_source_id'), 'currency', ['code', 'data_source_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
