"""change currency uc

Revision ID: dc75c5dd6757
Revises: 942bb70c2208
Create Date: 2025-08-13 18:08:42.725782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc75c5dd6757'
down_revision: Union[str, Sequence[str], None] = '942bb70c2208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_currency_code'), 'currency', type_='unique')
    op.create_unique_constraint('uix_code_data_source_id', 'currency', ['code', 'data_source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_code_data_source_id', 'currency', type_='unique')
    op.create_unique_constraint(op.f('uq_currency_code'), 'currency', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
