"""empty message

Revision ID: 4dad2731b185
Revises: 4acd355e341c
Create Date: 2025-08-20 17:59:37.955456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dad2731b185'
down_revision: Union[str, Sequence[str], None] = '4acd355e341c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_currency_date_base'), 'currency_rate', type_='unique')
    op.create_unique_constraint('uix_currency_date_base', 'currency_rate', ['currency_id', 'date', 'base_currency_id', 'data_source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_currency_date_base', 'currency_rate', type_='unique')
    op.create_unique_constraint(op.f('uix_currency_date_base'), 'currency_rate', ['currency_id', 'date', 'base_currency_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
